#!/usr/bin/env bash
# localhost is 127.0.0.2 and facebook.com is 8.8.8.8
sudo cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee /etc/hosts > /dev/null
